# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_type', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=100)),
                ('con_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('con_price', models.IntegerField()),
            ],
        ),
    ]
