# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consume',
            old_name='user_id',
            new_name='user',
        ),
    ]
