# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_book', '0002_consume_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Unknown', max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Unknown', max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
