# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_book', '0003_consumecategory_socialcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Con_ConCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_book.ConsumeCategory')),
                ('consume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_book.Consume')),
            ],
        ),
    ]
