# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_book', '0005_user_concategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_concategory',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_concategory',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ac_book.ConsumeCategory'),
        ),
        migrations.AlterField(
            model_name='user_concategory',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
