# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 17:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ac_book', '0007_auto_20161018_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_concategory',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_concategory',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_book.ConsumeCategory'),
        ),
        migrations.AlterField(
            model_name='user_concategory',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
